# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/JSON-GRDDL/project>
	:perl_version_from
		_:main;
	:version_from
		_:main;
	:readme_from
		_:main;
	:test_requires
		"Test::More 0.61";
	:requires
		"Carp 1.00",
		"common::sense",
		"JSON",
		"JSON::T",
		"LWP::UserAgent",
		"Object::AUTHORITY",
		"RDF::Trine 0.112",
		"Scalar::Util".

_:main
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>
		"lib/JSON/GRDDL.pm".

